AllCops:
  Exclude:
    - vendor/**/*

Metrics:
  Enabled: false

Metrics/LineLength:
  Max: 512

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Naming/MethodName:
  Enabled: false

inherit_from: .rubocop_todo.yml

inherit_from: .rubocop_todo.yml

